__include__: [
  '/home/featurize/zfy/DEIM/configs/dataset/pl_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]

print_freq: 1000
output_dir: ./outputs/dqs_dfine_s_pl

postprocessor: DQPostProcessor

DEIM:
  backbone: HGNetv2
  # encoder: HybridEncoder_DRE
  decoder: DQSDFINETransformer


HGNetv2:
  name: 'B0'
  return_idx: [0, 1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

DQSDFINETransformer:
  # feat_channels: [128, 128, 128]
  feat_channels: [256, 256, 256, 256]
  # feat_channels: [256, 256, 256]
  feat_strides: [4, 8, 16, 32]
  # feat_strides: [4, 8, 16]
  hidden_dim: 256
  num_levels: 4
  # num_levels: 3

  num_layers: 3
  eval_idx: -1
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0

  # NEW
  reg_max: 32
  reg_scale: 4

  # Auxiliary decoder layers dimension scaling
  # "eg. If num_layers: 6 eval_idx: -4,
  # then layer 3, 4, 5 are auxiliary decoder layers."
  layer_scale: 1  # 2


  num_points: [4, 4, 4, 4] # [4, 4, 4] [3, 6, 3]
  # num_points: [4, 4, 4] # [4, 4, 4] [3, 6, 3]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic

  dim_feedforward: 1024

  # using_densitymap_iter: 32085
  # using_densitymap_iter: 8090
  using_densitymap_iter: 17520
  using_dynamic_query: True
  use_ldmg: True
  use_cgfe: True 
  query_factor: 5

HybridEncoder:
# HybridEncoder:
  in_channels: [64, 256, 512, 1024]
  # in_channels: [64, 256, 512]
  feat_strides: [4, 8, 16, 32]
  # feat_strides: [4, 8, 16]
  hidden_dim: 256
  # hidden_dims: [128, 128, 128]
  # encoder_out_channels: [128, 128, 128]
  expansion: 0.5
  depth_mult: 0.34

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0001
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0001
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.000065

lr_scheduler:
  type: MultiStepLR
  milestones: [180, 240]
  gamma: 0.8

# Increase to search for the optimal ema
epoches: 300 # 148 + 4n
train_dataloader:
  total_batch_size: 4
  dataset:
    transforms:
      ops:
        # - {type: Mosaic, probability: 0.5}
        # - {type: MixUp, alpha: 1.5, p: 0.2}
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomZoomOut, fill: 0}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [640, 640], } 
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        # name: stop_epoch
        epoch: 240 # epoch in [71, ~) stop `ops`
        ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
        # ops: ['Mosaic', 'MixUp', 'RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  collate_fn:
    base_size: 640
    stop_epoch: 240
    ema_restart_decay: 0.9999
    base_size_repeat: 2

val_dataloader:
  dataset:
    transforms:
      type: Compose
      ops:
        - {type: Resize, size: [640, 640], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  total_batch_size: 4

DEIMCriterion:
  # weight_dict: {loss_vfl: 1.1, loss_bbox: 7.5, loss_giou: 3, loss_fgl: 0.15, loss_ddf: 1.5, loss_densitymap: 5, loss_densitycount: 0.2}
  # weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5, loss_densitymap: 10, loss_densitycount: 0.2}
  # losses: ['vfl', 'boxes', 'local', 'densitymap', 'densitycount']
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2, loss_fgl: 0.15, loss_ddf: 1.5, loss_densitymap: 10}
  losses: ['vfl', 'boxes', 'local', 'densitymap']

  # density_precision_penalty: 1.3
  # density_recall_penalty: 1.1
  density_precision_penalty: 1.1
  density_recall_penalty: 1.3

  no_weight_vfl_epoch: 20