__include__: [
  '/home/featurize/zfy/DEIM/configs/dataset/uavdt_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]

print_freq: 1600
output_dir: ./outputs/dfine_m_uavdt

remap_mscoco_category: False
yolo_metrice: False


DEIM:
  backbone: HGNetv2
  decoder: DFINETransformer

HGNetv2:
  name: 'B2'
  return_idx: [0, 1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True

HybridEncoder:
  in_channels: [96, 384, 768, 1536]
  feat_strides: [4, 8, 16, 32]
  hidden_dim: 256
  depth_mult: .67

DFINETransformer:
  feat_channels: [256, 256, 256, 256]
  feat_strides: [4, 8, 16, 32]
  hidden_dim: 256
  num_levels: 4

  num_layers: 4
  eval_idx: -1
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0

  num_points: [4, 4, 4, 4] # [4, 4, 4] [3, 6, 3]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic


optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00002
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00001
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0002
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 160 # 272 + 4n
train_dataloader:
  dataset:
    transforms:
      # ops:
      #   - {type: RandomPhotometricDistort, p: 0.5}
      #   - {type: RandomZoomOut, fill: 0}
      #   - {type: RandomIoUCrop, p: 0.8}
      #   - {type: SanitizeBoundingBoxes, min_size: 1}
      #   - {type: RandomHorizontalFlip}
      #   - {type: Resize, size: [640, 640], } 
      #   - {type: SanitizeBoundingBoxes, min_size: 1}
      #   - {type: ConvertPILImage, dtype: 'float32', scale: True}
      #   - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
  dataset:
    transforms:
      policy:
        epoch: 120
      # policy:
      #   # name: stop_epoch
      #   epoch: 120 # epoch in [71, ~) stop `ops`
      #   ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  num_workers: 1
  # pin_memory: False
  collate_fn:
    base_size: 640
    stop_epoch: 120
    ema_restart_decay: 0.9999
    base_size_repeat: 2
  total_batch_size: 4
val_dataloader:
  total_batch_size: 4
  # total_batch_size: 2


# CUDA_VISIBLE_DEVICES=0 python train.py -c /home/featurize/zfy/DEIM/configs/dfine/dfine_hgnetv2_m_uavdt.yml --seed=0