backbone:
  # [from, module, args]
  - [-1, nn.Identity, []]                                                          # 0
  - [0, GetRGBModalityTensor, []]                                                 # 1-RGB
  - [0, GetNPYModalityTensor, []]                                                 # 2-NPY

  - [1, StemBlock, [16, 16, True]]                                               # 3-P2/4
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']]                  # 4-P2/4
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']]                  # 5-P3/8
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]                   # 6-P4/16
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']]                 # 7-P5/32

  - [2, StemBlock, [16, 16, True]]                                                # 8-P2/4
  - [-1, HG_Stage, [16, 64, 1, 3, False, False, 3, True, 'se']]                  # 9-P2/4
  - [-1, HG_Stage, [32, 256, 1, 3, True, False, 3, True, 'se']]                  # 10-P3/8
  - [-1, HG_Stage, [64, 512, 2, 3, True, True, 5, True, 'se']]                   # 11-P4/16
  - [-1, HG_Stage, [128, 1024, 1, 3, True, True, 5, True, 'se']]                 # 12-P5/32

  - [[5, 10], Concat, []]                                                         # 13-P3/8
  - [[6, 11], Concat, []]                                                         # 14-P4/16
  - [[7, 12], Concat, []]                                                         # 15-P5/32

encoder:
  - [14, ConvNormLayer_fuse, [128, 1, 1]]                                         # 16-P4/16
  - [15, ConvNormLayer_fuse, [128, 1, 1]]                                         # 17-P5/32

  - [-1, TransformerEncoderBlock, [8, 512, 0.1, "relu", 10000, False]]            # 18-P5/32

  - [-1, ConvNormLayer_fuse, [128, 1, 1]]                                         # 19
  - [-1, nn.Upsample, [None, 2, "nearest"]]                                       # 20
  - [[-1, 14], Concat, []]                                                        # 21-P4/16
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']]                          # 22-P4/16

  - [-1, SCDown, [128, 3, 2, 'silu']]                                             # 23-P5/32
  - [[-1, 19], Concat, []]                                                        # 24-P5/32
  - [-1, RepNCSPELAN4, [128, 256, 21, 2, False, 'silu']]                          # 25-P5/32

decoder:
  - [[22, 25], DFINETransformer, {"feat_strides":[16, 32], "hidden_dim": 128, "num_levels": 2, "num_layers": 3, "num_points": [6, 6], "dim_feedforward": 512}]